export const REGISTER_EMAIL_CHANGED = 'REGISTER_EMAIL_CHANGED';
export const REGISTER_USERNAME_CHANGED = 'REGISTER_USERNAME_CHANGED';
export const REGISTER_PASSWORD_CHANGED = 'REGISTER_PASSWORD_CHANGED';
export const REGISTER_CONFIRM_PASSWORD_CHANGED = 'REGISTER_CONFIRM_PASSWORD_CHANGED';
export const REGISTER_CONFIRM_EMAIL_CHANGED = 'REGISTER_CONFIRM_EMAIL_CHANGED';

// Login Form
export const LOGIN_EMAIL_CHANGED = 'LOGIN_EMAIL_CHANGED';
export const LOGIN_PASSWORD_CHANGED = 'LOGIN_PASSWORD_CHANGED';